In [0]:
import numpy as np
import random

https://stats.stackexchange.com/questions/179835/how-to-build-a-confusion-matrix-for-a-multiclass-classifier

In [10]:
confusion = np.random.randint(10, size=(10, 10))
for i in range(10):
  confusion[i][i] = random.randint(100, 200)
confusion

array([[160,   0,   1,   3,   0,   8,   6,   2,   8,   5],
       [  2, 137,   1,   2,   8,   7,   8,   8,   0,   3],
       [  4,   0, 200,   8,   4,   9,   3,   8,   0,   0],
       [  6,   4,   0, 133,   6,   0,   6,   5,   8,   9],
       [  8,   8,   7,   9, 178,   1,   6,   7,   0,   2],
       [  8,   7,   4,   7,   0, 198,   8,   2,   0,   2],
       [  8,   0,   1,   4,   3,   7, 167,   8,   0,   2],
       [  4,   6,   0,   2,   9,   9,   9, 103,   5,   7],
       [  7,   5,   1,   0,   1,   7,   9,   7, 177,   1],
       [  1,   2,   1,   4,   2,   8,   2,   2,   7, 123]])

https://stats.stackexchange.com/a/338240


In [20]:
true_positive = np.zeros(10)
for i in range(10):
  true_positive[i] = confusion[i][i]
true_positive

array([160., 137., 200., 133., 178., 198., 167., 103., 177., 123.])

In [22]:
s = np.sum(confusion, axis=0)
false_positive = np.zeros(10)
for i in range(10):
  false_positive[i] = s[i] - true_positive[i]
false_positive

array([48., 32., 16., 39., 33., 56., 57., 49., 28., 31.])

In [23]:
s = np.sum(confusion, axis=1)
false_negative = np.zeros(10)
for i in range(10):
  false_negative[i] = s[i] - true_positive[i]
false_negative

array([33., 39., 36., 44., 48., 38., 33., 51., 38., 29.])

In [24]:
s = np.sum(np.sum(confusion, axis=1))
true_negative = np.zeros(10)
for i in range(10):
  true_negative[i] = s - true_positive[i] - false_positive[i] - false_negative[i]
true_negative

array([1724., 1757., 1713., 1749., 1706., 1673., 1708., 1762., 1722.,
       1782.])

https://towardsdatascience.com/understanding-data-science-classification-metrics-in-scikit-learn-in-python-3bc336865019

In [27]:
accuracy = (true_positive + true_negative)/(true_positive + true_negative + false_positive + false_negative)
accuracy

array([0.95877863, 0.96386768, 0.9735369 , 0.95776081, 0.95877863,
       0.95216285, 0.95419847, 0.94910941, 0.96641221, 0.96946565])

In [31]:
np.sum(accuracy)/10

0.9604071246819339

In [29]:
recall = (true_positive)/(true_positive + false_negative)
recall

array([0.82901554, 0.77840909, 0.84745763, 0.75141243, 0.78761062,
       0.83898305, 0.835     , 0.66883117, 0.82325581, 0.80921053])

In [32]:
np.sum(recall)/10

0.7969185870864648

In [33]:
precision = (true_positive)/(true_positive + false_positive)
precision

array([0.76923077, 0.81065089, 0.92592593, 0.77325581, 0.8436019 ,
       0.77952756, 0.74553571, 0.67763158, 0.86341463, 0.7987013 ])

In [34]:
np.sum(precision)/10

0.7987476077554587

In [35]:
f1 = (2 * precision * recall)/(precision + recall)
f1

array([0.79800499, 0.7942029 , 0.88495575, 0.76217765, 0.81464531,
       0.80816327, 0.78773585, 0.67320261, 0.84285714, 0.80392157])

In [37]:
np.sum(f1)/10

0.7969867037874975